### ISSUE TITLE
Share functionality

### ISSUE THREAD

**Issue by Jsuppers** [Jsuppers/axie-pad#86]
I would really like to be able to share what axies I have with friends, this is probably going to be a big PR:

1. Add a share button in the finder tab:
![image](https://user-images.githubusercontent.com/34351874/140665587-12444a05-a6c9-498a-a7b8-5ef6503c8823.png)

2. This button will open a dialog where you can select the scholars you want to share or not e.g. 
![image](https://user-images.githubusercontent.com/34351874/140665795-dfde2e5a-93f3-4816-985a-ac4b68447df0.png)
"By selecting the scholars, you are sharing allowing anyone with this link to see the axies you have for this scholar. Be careful who you give this link to! "

3. when selecting the scholars (or add all), it will save the ronin addresses to another collected /users/<user_id>/shared e.g. 
![image](https://user-images.githubusercontent.com/34351874/140665854-560442c8-766d-4b3f-a147-8b902afb7597.png)
![image](https://user-images.githubusercontent.com/34351874/140665903-9026e97a-525e-482a-a700-ac19bc5f310c.png)

4. add a new page https://axiepad.com/#/user/<user_id> which just shows the finder tab (without the share button):
![image](https://user-images.githubusercontent.com/34351874/140665949-ebc0958d-f1b5-4e7b-b86c-bf47c1899c8c.png)

**Comment by Jsuppers** [comment]
I have already added the rule in firebase rules so anyone should be able to read from the shared collection i.e

![image](https://user-images.githubusercontent.com/34351874/140666059-284eea33-538a-455a-858d-4997ef191043.png)

**Comment by nnkhuongduy** [comment]
Is this the correct way to access the 'shared' collection on user? If so I got this permission error when trying to access it, can you help me check it?
![image](https://user-images.githubusercontent.com/60511087/140887157-084174ab-8a9d-4ebc-b436-6bef072ffc93.png)
![image](https://user-images.githubusercontent.com/60511087/140887326-11a3d9f2-401e-42e8-be04-01e738ca6b65.png)

**Comment by Jsuppers** [comment]
> Is this the correct way to access the 'shared' collection on user? If so I got this permission error when trying to access it, can you help me check it? ![image](https://user-images.githubusercontent.com/60511087/140887157-084174ab-8a9d-4ebc-b436-6bef072ffc93.png) ![image](https://user-images.githubusercontent.com/60511087/140887326-11a3d9f2-401e-42e8-be04-01e738ca6b65.png)

it is a subcollection so something like this should work: .collection('users/' + this._uid + '/shared') let me know if it doesnt :)

**Comment by nnkhuongduy** [comment]
This is what I changed to but it still gave me the permission error
![image](https://user-images.githubusercontent.com/60511087/141079288-1d1bc13a-02e2-4795-88ea-651947bf7713.png)

**Comment by Jsuppers** [comment]
> This is what I changed to but it still gave me the permission error ![image](https://user-images.githubusercontent.com/60511087/141079288-1d1bc13a-02e2-4795-88ea-651947bf7713.png)

ah yes sorry was a firebase issue, just updated it and pushed some changes
